Repository kevin2526/Competitive-Coding-Solutions, pull requests merged in 2022-10, with the labels that each got.

#2 feat: Add Dijkstra Algorithm
  dijkstra.cpp
Labels: hacktoberfest

#3 Add LCA Algorithm in Graphs
  Graph/lca.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#4 Add CF solutions
  CF/1500/1744.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#5 Add CF Solution for 1738C.cpp
  CF/1500/1738C.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, cf

#7 Add 1.cpp
  CF/1500/1.cpp
Labels: hacktoberfest, hacktoberfest-accepted, cf
